# Currently Active Working Groups / Committees 

The following describe currently active working groups listed in alphabetical
order. If you are interested in becoming involved with one of these groups
please contact the group leader(s).


## BiocAsia

- Description: This group will primarily be involved with conference planning for the BiocAsia conference and seeks to formalise this as a Bioconductor Working Group
- Slack: #biocasia-conference-organization, #biocasia
- Leads: Stevie Pederson, Stefano Mangiola
- Current Members: Stevie, Stefano, Ellis Patrick, Peter Hickey, Kozo Nishida, Jiya Chaudhary, Manoj Wagle, Lori Shepherd

## BiocAwards

- Description: In 2020, Bioconductor established annual Bioconductor awards to
recognize outstanding contributions to the Bioconductor community. This
committee meets annually starting roughly 4-6 months before the annual
conference to conduct nominations and voting. 
- Links: https://bioconductor.org/about/awards/
- Leads: Lori Shepherd <Lori.Shepherd@RoswellPark.org> and Maria Doyle
- Current Members: Stevie Pederson, Johannes Rainer

## Classes and Methods Recommendations

- Description: Discussions arounnd Bioconductor 'official' classes and methods
  and how to articulate their benefits to increase their usage across the
  ecosystem, in particular in new contributions. Contemplation of how to
  integrate S7 framework.
- Slack: #biocclasses
- Links: https://github.com/Bioconductor/BiocClassesWorkingGroup
- Leads: Laurent Gatto, Michael Lawrence, Lori Shepherd
- Current Members: Vince Carey, Laurent Gatto, Michael Lawrence, Marcel Ramos,
  Lluis Revilla, Dario Righelli, Lori Shepherd, Malte Thodberg, Tim Triche  

## Cloud Methods

- Description: The goal of this group is to develop standards and tools for the
  Bioconductor community that are related to the cloud.
- Slack: #cloud-working-group
- Leads: Erdal Cosgun
- Current Members: Mike Smith, Levi Waldron, Tyrone Lee, Marcel Ramos, Brian Schilder, 
  Alex Mahmoud, Jen Wokaty, Ludwig Geistlinger, Sean Davis, Vince Carey

## Code of Conduct

- Description: The Code of Conduct Committee reviews and revises the
  Bioconductor Code of Conduct as needed. There is also a large effort to
  translate the Code of Code to multiple languages.
- Links: https://github.com/Bioconductor/bioc_coc_multilingual
- Slack: private channel
- Leads: Anna Quaglieri, Gerry Tonkin-Hill
- Current Members: Kevin Rue-Albrecht, Martin Davila-Cervantes, Federica
  Gazzelloni, Michael Love, Federico Marini, Sowmya Parthiban, Shixiang Wang,
  Lluis Revilla, Paulina Boadiwaa Mensah, Peace Sandy, Sinmisoluwa Adesanya,
  Michella Savage

## Conference Planning

- Description: Organizes and Plans the Annual Conference.
- Slack: #bioc-conference-organization, #bioc-conference-everyone
- Leads: Levi Waldron, Erica Feick
- Current Members: Charlotte Soneson, Jenny D, Jenny S, Lori, Marc, Andrew, Daniela, Matt, Mikhail, Samuel, Krithika, Sean, Wes

## EDAM collaboration

- Description: This group unites EDAM and Bioconductor community members to explore indexing the Bioconductor ecosystem using the [EDAM ontology](https://edamontology.org/). Our working group's objectives include increasing the visibility of Bioconductor packages to a broader audience, including those not primarily using R, and expanding EDAM as a standard for annotating computational biology resources. Through this collaboration, we aim to synergize two large, international communities focused on open science. Future plans may include exploring connections with bio.tools, Bioschemas, and TeSS. If you're interested in contributing or want to learn more, join us on Slack.
- Slack: #edam-collaboration
- Leads: Claire Rioualen, Maria Doyle, Hervé Pagès
- Current Members: Vince Carey, Hervé Menager, Lori Shepherd, Johannes Rainer, Kozo Nishida, Matúš Kalaš

## Education

- Description: The Bioconductor teaching and education committee is a collaborative effort to consolidate Bioconductor-focused training material and establish a community of Bioconductor trainers. We define a curriculum and implement online lessons for beginner and more advanced R users who want to learn to analyse their data with Bioconductor packages.
- Links: https://github.com/bioconductor/bioconductor-teaching
- Slack: #education-and-training
- Leads: Laurent Gatto, Charlotte Soneson, Kevin Rue-Albrecht
- Founding Members: Laurent Gatto, Charlotte Soneson, Kevin Rue-Albrecht, Jenny Drnevich, Robert Castelo, Toby Hodges, Susan Holmes
- Current Members: Open to all. Join us! Details [here](https://www.bioconductor.org/help/education-training/).

## Mass Spectrometry for Proteomics and Metabolomics

- Description: The goal of this working group is to identify members of the
  Bioconductor community that are interested and/or active in the area of mass
  spectrometry, proteomics and/or metabolomics and define technical needs or
  community expectations to prioritise future developments.
- Links: https://github.com/lgatto/BiocMassSpecWorkingGroup
- Slack: #mass-spectrometry, #metabolomics, #proteomics
- Leads: Laurent Gatto (TAB) and Johannes Rainer (CAB) 
- Current Members: Lauent, Johannes. 

## Multilingual

- Description: The multiligual group is focused on translating and hosting
  Bioconductor material in multiple languages. Help is always appreciated!
- Slack: #documentation-translation

### Code of Conduct Translation  
- Links: [CoC](https://github.com/Bioconductor/bioc_coc_multilingual), [talks_and_transcripts](https://github.com/BioconductorBoards/CABWorkingGroups/tree/main/talks_and_transcripts)
- Leads: Leonardo Collado-Torres, Kozo Nishida, Daniela Cassol, Kevin Rue-Albrecht, Dario Righelli.

### French Translation Subgroup
- Description: Focused on translating Bioconductor Carpentries lessons into French.
- Current Members: Marie Hidjo (co-lead), Laurent Gatto (co-lead), Susan Holmes, Laura Symul.
- Slack:  #translation-fr

### Spanish Translation Subgroup
- Description: Focused on translating Bioconductor Carpentries lessons into Spanish.
- Leads: Robert Castelo (lead), Javier Carpinteyro Ponce
- Current Members:
- Slack:  #translation-es

## Package Build Report Triage

- Description: This committee would be responsible for reaching out to ERRORing
  package maintainers to fix their package and identify inactive packages for
  deprecation. While we have autonotificaiton of failure, many (most)
  maintainers ignore and are not good about checking the provided build
  reports. The core team has found that sending personalized emails greatly
  increases the likelihood of a maintainer to fix the package.
- Links: https://bioconductor.org/checkResults/
- Leads: Lori Shepherd <Lori.Shepherd@RoswellPark.org> 
- Current Members: Johannes Rainer, Kayla Interdonato. I need more members! Please if interested
  please email or slack

## R-Ladies and Bioc

- Description: The R-Ladies working group aims to foster collaboration between Bioconductor
  and R-Ladies to encourage, support, and promote gender minorities at the
  intersection of computational biology/bioinformatics and data science. We will
  achieve this through co-hosted events, blog posts, and other collaborative initiatives.
- Links:
- Slack: #r-ladies
- Leads: Janani Ravi
- Current Members: Janani Ravi, Daniela Cassol, Aedin Culhane, Lori Shepherd,
  Stephanie Hicks, Heather Turner

## Social Media

- Description: Group for creating Bioconductor strategy, guidelines etc for social media (Blog, Twitter, Mastodon, YouTube, LinkedIn, Instagram, TikTok, Bilibili, WeChat, Weibo...).
- Links: 
- Slack: #social-media
- Leads: Maria Doyle
- Current Members: Laurent Gatto, Susan Holmes, Federica Gazzelloni, İrem Kahveci, Hamdi Furkan Kepenek, Xueyi Dong, Shixiang Wang, Kozo Nishida

## TeSS

- Description: This group focuses on enhancing the connectivity and integration between the [TeSS (Training eSupport System)](https://tess.elixir-europe.org) portal and the Bioconductor project. Our objectives include implementing Bioschemas for Bioconductor training material and events to improve their discoverability and accessibility via TeSS (https://tess.elixir-europe.org/content_providers/bioconductor). We aim to strengthen the bridge between these platforms, facilitating easier access to Bioconductor training resources.
- Slack: #elixir. A TeSS-specific channel may be created based on interest and participation.
- Leads: Maria Doyle
- Current Members: Maria Doyle, Laurent Gatto (contact Maria on Slack if interested to join this initiative)

## Website

- Description: The Website working group will create the list of requirements for the Bioconductor website redesign.
- Links: 
- Slack: #biocwebsite
- Leads: Maria Doyle, Lori Shepherd, Aedin Culhane 
- Current Members: Kevin Rue-Albrecht, Sean Davis, Susan Holmes, Vince Carey, Alex Mahmoud, Marcel Ramos, Hédia Thani, Shila Ghazanfar, Laurent Gatto, Jen Wokaty, Samuel Gamboa, Bob Shear, Matt Ritchie

## Workflows

- Description: This group is focussed on updating and rebranding Bioconductor Workflows as well as streamlining arrangements with an external publisher, specifically for workflows. 
- Links:
- Slack: #workflows
- Leads: Michael Love
- Current Members: Charlotte Soneson, Davide Risso, Lori Shepherd, Stevie Pederson, Susan Holmes, Ellis Patrick, Sean Davis, Aedin Culhane, Vince Carey, Janani Ravi, Woflgang Huber
