# Needed Working Groups / Committees

<p>This is a list of suggested working groups / committees with intended
focus. These groups still need a lead to organize and move the project goals
forwards.  If you are interested in starting one of these listed working groups
please contact Lori.Shepherd@RoswellPark.org.</p>

<p>If you have an idea for a working group or committee that is not currently
active or listed here, you can either contact Lori.Shepherd@Roswellpark.org or
submit a pull requested providing Description, Lead, Initial Members, and any
other relevent links.</p>

## Developers Training

- Description: This group aims to help create and promote development
  discussions and opportunities within the Bioconductor organization. This
  includes organizing developer forum talks, collating material on the
  Bioconductor YouTube channel, and monitoring the new developer mentorship
  program.
- Links: [New Developer Training Program](http://bioconductor.org/developers/new-developer-program/), [Playlist on Bioconductor YouTube](https://www.youtube.com/watch?v=CcJgcDy2qEI&list=PLdl4u5ZRDMQQLMupAtEzm2y4gUIUm_1n6)
- Slack: #developers-mentorship, #developers-forum
- Leads: Mike Smith, Kevin Rue-Albrecht
- Current Members: Aedin Culhane, Lori Shepherd

## Industry

- Description: Many Bioconductor users are from industry. Yet industry users aren't a large voice in the Bioconductor community. This working group is centered around collaborating and engaging with industry users. Topics of interest include: how to get more industry users participating with the community, what guidelines can be established to bolster the community relationship with industry, and much more.
- Links:
- Slack: #industry
- Leads: Nicole Ortogero, David Henderson
- Current Members: Michael Lawrence, Xiuwen Zheng, Wade Davis, Snehal Wani, Scott Chasalow

## Privacy

- Description: Data privacy is an important topic to the Bioconductor project, 
with its large community and many websites and services hosted by a variety of
organisations around the globe.  This working group is engaged in making sure 
that Bioconductor services meet both legal requirements and community 
expectations regarding personal data privacy.
- Links:
- Leads:
- Current Members: Vince Carey, Mike Smith
- Past Members: Katermina Kechris

## Publication

- Description: Publication discussion with F1000R and other venues that enable publication of workflows, BioC material from workshops or package presentations. This working group is trying to make it easier and less expensive to publish papers on BioC advances that can be kept up to date while still providing DOI and valid publication metadata so that there is a citation and recognition mechanism. Highly interested in new Overlay publishing and using quarto for new publication models.
- Links:
- Leads: Susan Holmes
- Current Members: Susan, Sean Davis,

## Spatial and Multi-omics

- Description:
- Links:
- Leads: 
- Current Members: 


